use crate::ast::*;
use crate::check;
use crate::diag::{Diagnostic, Severity};
use crate::ir::{Ir, IrNode};
use crate::profile;
use crate::sexpr::Sexpr;
use std::collections::{HashMap, HashSet};

/// Elaborate a parsed file: expand profiles, check, lower to IR.
/// Diagnostics from checking and elaboration are folded into the IR;
/// the caller inspects Ir::has_errors().
pub fn elaborate(file: &File) -> Ir {
    let mut elaborator = Elaborator::new(&file.spec.name.text);

    // Step 1: Profile expansion. Each entry carries the profile name it
    // was generated by (None for declarations written in the source).
    let expanded_decls = elaborator.expand_profiles(&file.decls);
    let mut all_diags: Vec<Diagnostic> = Vec::new();

    // Step 2: Check the expanded declarations
    let temp_file = File {
        spec: file.spec.clone(),
        decls: expanded_decls.iter().map(|(d, _)| d.clone()).collect(),
    };
    let check_diags = check::check(&temp_file);
    all_diags.extend(check_diags);

    // Lower parse/check diagnostics to IR format
    let mut ir_diags = lower_diagnostics(&all_diags);

    // Step 3: Lower all declarations; profile-generated nodes carry a
    // :profile-source field so provenance survives into the IR.
    let mut all_nodes = Vec::new();
    let mut node_spans = Vec::new();
    for (decl, source) in &expanded_decls {
        if let Some(node) = elaborator.lower_decl(decl) {
            let node = match source {
                Some(profile_name) => {
                    let mut fields = node.fields.clone();
                    fields.push((":profile-source".to_string(), Sexpr::sym(profile_name)));
                    IrNode::new(node.id, &node.kind, node.name, fields, node.clauses)
                }
                None => node,
            };
            all_nodes.push(node);
            node_spans.push(decl_span(decl));
        }
    }

    // Step 4: Detect duplicate semantic IDs; the span points at the
    // duplicate declaration itself.
    let mut seen_ids = HashSet::new();
    for (node, span) in all_nodes.iter().zip(node_spans.iter()) {
        if !seen_ids.insert(&node.id) {
            ir_diags.push(diag_sexpr(
                "error",
                "E301",
                (span.start as i64, span.end as i64),
                format!("duplicate-semantic-id: {}", node.id),
            ));
        }
    }

    // Add elaborator diagnostics
    for diag in &elaborator.elab_diags {
        ir_diags.push(diag.clone());
    }

    // Step 5: Partition nodes by kind
    let mut design = Vec::new();
    let mut transitions = Vec::new();
    let mut obligations = Vec::new();
    let mut synthesis = Vec::new();

    for node in all_nodes {
        match node.kind.as_str() {
            "import" | "application" | "actor" | "type" | "component" | "interface" | "state"
            | "flow" => design.push(node),
            "behavior" => transitions.push(node),
            "invariant" | "constraint" | "acceptance" => obligations.push(node),
            "synthesis" => synthesis.push(node),
            _ => {
                // Unknown kind - shouldn't happen if lowering is correct
                design.push(node);
            }
        }
    }

    // Module fields come from the spec header.
    let module_fields = vec![
        (
            ":exports".to_string(),
            Sexpr::list(
                file.spec
                    .exports
                    .iter()
                    .map(|e| Sexpr::sym(&e.text))
                    .collect(),
            ),
        ),
        (":owner".to_string(), Sexpr::sym(&file.spec.owner.text)),
        (
            ":version".to_string(),
            Sexpr::Str(file.spec.version.clone()),
        ),
    ];

    // Build IR with partitioning and sorting
    let ir = Ir::new(
        "gymnast.ir/0.1".to_string(),
        elaborator.module_name.clone(),
        module_fields,
        design,
        transitions,
        obligations,
        synthesis,
        ir_diags,
    );

    ir
}

struct Elaborator {
    module_name: String,
    elab_diags: Vec<Sexpr>,
}

impl Elaborator {
    fn new(module_name: &str) -> Self {
        Elaborator {
            module_name: module_name.to_string(),
            elab_diags: Vec::new(),
        }
    }

    fn expand_profiles(&mut self, decls: &[Decl]) -> Vec<(Decl, Option<String>)> {
        let mut expanded = Vec::new();

        for decl in decls {
            expanded.push((decl.clone(), None));

            // If this is a Use declaration, try to expand it
            if let Decl::Use(use_decl) = decl {
                let profile_name = use_decl
                    .path
                    .iter()
                    .map(|i| i.text.clone())
                    .collect::<Vec<_>>()
                    .join("/");
                let profile_version = use_decl.version.clone();

                match profile::lookup(&profile_name, &profile_version) {
                    Some(prof) => {
                        // Validate required parameters
                        let mut args_map: HashMap<String, Sexpr> = HashMap::new();
                        for item in &use_decl.args {
                            let key = item.key.text.clone();
                            let value = pack_value_to_sexpr(&item.value);
                            args_map.insert(key, value);
                        }

                        let mut missing_required = false;
                        for param in &prof.params {
                            if matches!(param.default, profile::ParamDefault::Required) {
                                if !args_map.contains_key(param.key) {
                                    self.elab_diags.push(diag_sexpr(
                                        "error",
                                        "E302",
                                        (use_decl.span.start as i64, use_decl.span.end as i64),
                                        format!("missing-profile-decision: {} required", param.key),
                                    ));
                                    missing_required = true;
                                }
                            }
                        }

                        // If no missing required params, generate declarations.
                        // Arguments are handed to the generator in declared
                        // parameter order — never HashMap order — so
                        // expansion stays deterministic.
                        if !missing_required {
                            let args_vec: Vec<(String, Sexpr)> = prof
                                .params
                                .iter()
                                .filter_map(|p| {
                                    args_map.get(p.key).map(|v| (p.key.to_string(), v.clone()))
                                })
                                .collect();
                            let generated = (prof.generate)(&args_vec);
                            for gen_decl in generated {
                                expanded.push((gen_decl, Some(profile_name.clone())));
                            }
                        }
                    }
                    None => {
                        self.elab_diags.push(diag_sexpr(
                            "warning",
                            "W303",
                            (use_decl.span.start as i64, use_decl.span.end as i64),
                            format!("unknown-profile: {}", profile_name),
                        ));
                    }
                }
            }
        }

        expanded
    }

    fn lower_decl(&self, decl: &Decl) -> Option<IrNode> {
        match decl {
            Decl::Use(use_decl) => self.lower_use(use_decl),
            Decl::Application(app) => self.lower_application(app),
            Decl::Actor(actor) => self.lower_actor(actor),
            Decl::Mode(mode) => self.lower_mode(mode),
            Decl::Component(comp) => self.lower_component(comp),
            Decl::Interface(iface) => self.lower_interface(iface),
            Decl::State(state) => self.lower_state(state),
            Decl::Flow(flow) => self.lower_flow(flow),
            Decl::Behavior(behavior) => self.lower_behavior(behavior),
            Decl::Invariant(inv) => self.lower_invariant(inv),
            Decl::Constraint(constr) => self.lower_constraint(constr),
            Decl::Synthesis(synth) => self.lower_synthesis(synth),
            Decl::Acceptance(acc) => self.lower_acceptance(acc),
        }
    }

    fn lower_use(&self, use_decl: &UseDecl) -> Option<IrNode> {
        let mut fields = vec![(":version".to_string(), Sexpr::Str(use_decl.version.clone()))];

        // Arguments as nested list
        let mut args_list = Vec::new();
        for item in &use_decl.args {
            let key = item.key.text.clone();
            let value = pack_value_to_sexpr(&item.value);
            args_list.push(Sexpr::list(vec![Sexpr::sym(&key), value]));
        }
        fields.push((":arguments".to_string(), Sexpr::list(args_list)));

        fields.push((":authority".to_string(), Sexpr::sym("authoritative")));

        let id = format!(
            "{}/import/{}",
            self.module_name,
            use_decl
                .path
                .iter()
                .map(|i| i.text.clone())
                .collect::<Vec<_>>()
                .join("/")
        );
        let name = use_decl
            .path
            .iter()
            .map(|i| i.text.clone())
            .collect::<Vec<_>>()
            .join("/");

        Some(IrNode::new(id, "import", name, fields, vec![]))
    }

    fn lower_application(&self, app: &ApplicationDecl) -> Option<IrNode> {
        let fields = pack_to_fields(&app.attrs);
        let id = format!("{}/application/{}", self.module_name, app.name.text);

        Some(IrNode::new(
            id,
            "application",
            app.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_actor(&self, actor: &ActorDecl) -> Option<IrNode> {
        let mut fields = vec![(":kind".to_string(), Sexpr::sym(&actor.kind.text))];
        fields.extend(pack_to_fields(&actor.attrs));
        let id = format!("{}/actor/{}", self.module_name, actor.name.text);

        Some(IrNode::new(
            id,
            "actor",
            actor.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_mode(&self, mode: &ModeDecl) -> Option<IrNode> {
        let mode_fields = mode_expr_to_shape_field(&mode.expr);
        let fields = vec![mode_fields];
        let id = format!("{}/type/{}", self.module_name, mode.name.text);

        Some(IrNode::new(
            id,
            "type",
            mode.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_component(&self, comp: &ComponentDecl) -> Option<IrNode> {
        let fields = pack_to_fields(&comp.attrs);
        let id = format!("{}/component/{}", self.module_name, comp.name.text);

        Some(IrNode::new(
            id,
            "component",
            comp.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_interface(&self, iface: &InterfaceDecl) -> Option<IrNode> {
        let fields = vec![(":for".to_string(), Sexpr::sym(&iface.default_actor.text))];

        let mut clauses = Vec::new();
        for op in &iface.ops {
            let clause = self.lower_op_to_clause(op, &iface.default_actor.text);
            clauses.push(clause);
        }

        let id = format!("{}/interface/{}", self.module_name, iface.name.text);

        Some(IrNode::new(
            id,
            "interface",
            iface.name.text.clone(),
            fields,
            clauses,
        ))
    }

    fn lower_op_to_clause(&self, op: &OpDecl, default_actor: &str) -> Sexpr {
        let head = match op.kind {
            OpKind::Cmd => "command",
            OpKind::Qry => "query",
        };

        let mut items = vec![
            Sexpr::sym(head),
            Sexpr::sym(&op.name.text),
            Sexpr::sym(":actor"),
            Sexpr::sym(default_actor),
        ];

        // Input: record of params
        let mut param_pairs = Vec::new();
        for param in &op.params {
            let mode_sexpr = mode_expr_to_sexpr(&param.mode);
            param_pairs.push(Sexpr::list(vec![Sexpr::sym(&param.name.text), mode_sexpr]));
        }
        items.push(Sexpr::sym(":input"));
        items.push(Sexpr::list(vec![
            Sexpr::sym("record"),
            Sexpr::list(param_pairs),
        ]));

        // Output
        items.push(Sexpr::sym(":output"));
        items.push(mode_expr_to_sexpr(&op.output));

        // Errors
        items.push(Sexpr::sym(":errors"));
        let error_syms: Vec<Sexpr> = op.errors.iter().map(|e| Sexpr::sym(&e.text)).collect();
        items.push(Sexpr::list(error_syms));

        Sexpr::list(items)
    }

    fn lower_state(&self, state: &StateDecl) -> Option<IrNode> {
        let fields = pack_to_fields(&state.attrs);
        let id = format!("{}/state/{}", self.module_name, state.name.text);

        Some(IrNode::new(
            id,
            "state",
            state.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_flow(&self, flow: &FlowDecl) -> Option<IrNode> {
        let mut fields = vec![
            (":from".to_string(), Sexpr::sym(&flow.from.text)),
            (":to".to_string(), Sexpr::sym(&flow.to.text)),
            (":kind".to_string(), Sexpr::sym(&flow.kind.text)),
        ];
        fields.extend(pack_to_fields(&flow.attrs));
        let id = format!("{}/flow/{}", self.module_name, flow.name.text);

        Some(IrNode::new(
            id,
            "flow",
            flow.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_behavior(&self, behavior: &BehaviorDecl) -> Option<IrNode> {
        // :on = (interface/op actor request) - but we need binders from behavior
        let on_value = Sexpr::list(vec![
            Sexpr::sym(&format!(
                "{}/{}",
                behavior.on_interface.text, behavior.on_op.text
            )),
            if behavior.binders.len() > 0 {
                Sexpr::sym(&behavior.binders[0].text)
            } else {
                Sexpr::sym("actor")
            },
            if behavior.binders.len() > 1 {
                Sexpr::sym(&behavior.binders[1].text)
            } else {
                Sexpr::sym("request")
            },
        ]);

        let mut fields = vec![(":on".to_string(), on_value)];
        fields.extend(pack_to_fields(&behavior.attrs));

        let mut clauses = Vec::new();
        for clause in &behavior.clauses {
            clauses.push(self.lower_clause(clause));
        }

        let id = format!("{}/behavior/{}", self.module_name, behavior.name.text);

        Some(IrNode::new(
            id,
            "behavior",
            behavior.name.text.clone(),
            fields,
            clauses,
        ))
    }

    fn lower_clause(&self, clause: &Clause) -> Sexpr {
        match clause {
            Clause::Requires(pred) => {
                Sexpr::list(vec![Sexpr::sym("requires"), pred_to_sexpr(pred)])
            }
            Clause::Ensures(pred) => Sexpr::list(vec![Sexpr::sym("ensures"), pred_to_sexpr(pred)]),
            Clause::Returns(expr) => Sexpr::list(vec![Sexpr::sym("returns"), expr_to_sexpr(expr)]),
            Clause::Fails {
                error,
                when,
                preserves,
            } => {
                let mut items = vec![
                    Sexpr::sym("fails"),
                    Sexpr::sym(&error.text),
                    Sexpr::sym(":when"),
                    pred_to_sexpr(when),
                ];
                if let Some(preserve_ident) = preserves {
                    items.push(Sexpr::sym(":preserves"));
                    items.push(Sexpr::sym(&preserve_ident.text));
                }
                Sexpr::list(items)
            }
            Clause::Emits { event, qualifier } => {
                let mut items = vec![Sexpr::sym("emits"), Sexpr::sym(&event.text)];
                for q in qualifier {
                    items.push(Sexpr::sym(&q.text));
                }
                Sexpr::list(items)
            }
        }
    }

    fn lower_invariant(&self, inv: &InvariantDecl) -> Option<IrNode> {
        let fields = vec![
            (":scope".to_string(), Sexpr::sym(&inv.scope.text)),
            (":always".to_string(), pred_to_sexpr(&inv.always)),
        ];
        let id = format!("{}/invariant/{}", self.module_name, inv.name.text);

        Some(IrNode::new(
            id,
            "invariant",
            inv.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_constraint(&self, constr: &ConstraintDecl) -> Option<IrNode> {
        let mut fields = vec![
            (":class".to_string(), Sexpr::sym(&constr.class.text)),
            (":scope".to_string(), Sexpr::sym(&constr.scope.text)),
        ];

        // :under as nested list of (key value) pairs
        let mut under_pairs = Vec::new();
        for item in &constr.under {
            let key = item.key.text.clone();
            let value = pack_value_to_sexpr(&item.value);
            under_pairs.push(Sexpr::list(vec![Sexpr::sym(&key), value]));
        }
        fields.push((":under".to_string(), Sexpr::list(under_pairs)));

        fields.push((":must".to_string(), pred_to_sexpr(&constr.must)));

        let id = format!("{}/constraint/{}", self.module_name, constr.name.text);

        Some(IrNode::new(
            id,
            "constraint",
            constr.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_synthesis(&self, synth: &SynthesisDecl) -> Option<IrNode> {
        let mut target_items = vec![Sexpr::sym(&synth.target_lang.text)];
        if let Some(framework) = &synth.target_framework {
            target_items.push(Sexpr::sym(&framework.text));
        }
        let target_value = Sexpr::list(target_items);

        let mut fields = vec![(":target".to_string(), target_value)];
        fields.extend(pack_to_fields(&synth.attrs));

        let id = format!("{}/synthesis/{}", self.module_name, synth.name.text);

        Some(IrNode::new(
            id,
            "synthesis",
            synth.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_acceptance(&self, acc: &AcceptanceDecl) -> Option<IrNode> {
        let fields = vec![(":subject".to_string(), Sexpr::sym(&acc.subject.text))];

        let mut clauses = Vec::new();
        for block in &acc.blocks {
            clauses.push(self.lower_acceptance_block(block));
        }

        let id = format!("{}/acceptance/{}", self.module_name, acc.name.text);

        Some(IrNode::new(
            id,
            "acceptance",
            acc.name.text.clone(),
            fields,
            clauses,
        ))
    }

    fn lower_acceptance_block(&self, block: &AcceptanceBlock) -> Sexpr {
        match block {
            AcceptanceBlock::Property { name, body } => {
                let mut items = vec![Sexpr::sym("property"), Sexpr::sym(&name.text)];
                for item in body {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Scenario { name, steps } => {
                let mut items = vec![Sexpr::sym("scenario"), Sexpr::sym(&name.text)];
                for item in steps {
                    items.push(Sexpr::list(vec![
                        Sexpr::sym(&item.key.text),
                        pack_value_to_sexpr(&item.value),
                    ]));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Concurrency { name, attrs, must } => {
                let mut items = vec![Sexpr::sym("concurrency"), Sexpr::sym(&name.text)];
                for item in attrs {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                items.push(Sexpr::sym(":must"));
                items.push(pred_to_sexpr(must));
                Sexpr::list(items)
            }
            AcceptanceBlock::Fault { name, body } => {
                let mut items = vec![Sexpr::sym("fault"), Sexpr::sym(&name.text)];
                for item in body {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Coverage(names) => {
                let mut items = vec![Sexpr::sym("coverage")];
                for name in names {
                    items.push(Sexpr::sym(&name.text));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Execution(pack) => {
                let mut items = vec![Sexpr::sym("execution")];
                for item in pack {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                Sexpr::list(items)
            }
        }
    }
}

// Helper functions

fn pack_to_fields(pack: &Pack) -> Vec<(String, Sexpr)> {
    let mut fields = Vec::new();
    for item in pack {
        let key = format!(":{}", item.key.text);
        let value = pack_value_to_sexpr(&item.value);
        fields.push((key, value));
    }
    fields
}

fn pack_value_to_sexpr(value: &PackValue) -> Sexpr {
    match value {
        PackValue::Unit => Sexpr::sym("t"),
        PackValue::Word(w) => Sexpr::sym(&w.text),
        PackValue::Int(i) => Sexpr::Int(*i),
        PackValue::Str(s) => Sexpr::Str(s.clone()),
        PackValue::Quantity { value, unit } => {
            Sexpr::list(vec![Sexpr::sym(&unit.text), Sexpr::Int(*value)])
        }
        PackValue::List(items) => {
            let sexprs: Vec<Sexpr> = items.iter().map(|v| pack_value_to_sexpr(v)).collect();
            Sexpr::list(sexprs)
        }
        PackValue::Path(segs) => {
            let path_str = segs
                .iter()
                .map(|s| s.text.clone())
                .collect::<Vec<_>>()
                .join("/");
            Sexpr::sym(&path_str)
        }
        PackValue::Call { name, args } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            for arg in args {
                items.push(pack_value_to_sexpr(arg));
            }
            Sexpr::list(items)
        }
        PackValue::Nested(pack) => {
            let mut pairs = Vec::new();
            for item in pack {
                let key = item.key.text.clone();
                let value = pack_value_to_sexpr(&item.value);
                pairs.push(Sexpr::list(vec![Sexpr::sym(&key), value]));
            }
            Sexpr::list(pairs)
        }
    }
}

/// The declaration-level shape field: exactly one of :opaque, :enum,
/// :variant, or :record, mirroring the Lamedh type vocabulary.
fn mode_expr_to_shape_field(expr: &ModeExpr) -> (String, Sexpr) {
    match expr {
        ModeExpr::Opaque(inner) => (":opaque".to_string(), mode_expr_to_sexpr(inner)),
        ModeExpr::Enum(names) => {
            let syms: Vec<Sexpr> = names.iter().map(|n| Sexpr::sym(&n.text)).collect();
            (":enum".to_string(), Sexpr::list(syms))
        }
        ModeExpr::Union(variants) => {
            let pairs: Vec<Sexpr> = variants
                .iter()
                .map(|(tag, mode)| {
                    Sexpr::list(vec![Sexpr::sym(&tag.text), mode_expr_to_sexpr(mode)])
                })
                .collect();
            (":variant".to_string(), Sexpr::list(pairs))
        }
        ModeExpr::Struct(fields) => {
            let pairs: Vec<Sexpr> = fields
                .iter()
                .map(|f| Sexpr::list(vec![Sexpr::sym(&f.name.text), mode_expr_to_sexpr(&f.mode)]))
                .collect();
            (":record".to_string(), Sexpr::list(pairs))
        }
        other => (":opaque".to_string(), mode_expr_to_sexpr(other)),
    }
}

fn mode_expr_to_sexpr(expr: &ModeExpr) -> Sexpr {
    match expr {
        ModeExpr::Named { name, args } => {
            if args.is_empty() {
                Sexpr::sym(&name.text)
            } else {
                let mut items = vec![Sexpr::sym(&name.text)];
                for arg in args {
                    items.push(mode_expr_to_sexpr(arg));
                }
                Sexpr::list(items)
            }
        }
        ModeExpr::Refined { name, lo, hi } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            if let Some(lower) = lo {
                items.push(Sexpr::sym(":min"));
                items.push(Sexpr::Int(*lower));
            }
            if let Some(upper) = hi {
                items.push(Sexpr::sym(":max"));
                items.push(Sexpr::Int(*upper));
            }
            Sexpr::list(items)
        }
        ModeExpr::Opt(inner) => {
            Sexpr::list(vec![Sexpr::sym("Optional"), mode_expr_to_sexpr(inner)])
        }
        ModeExpr::Row(inner) => Sexpr::list(vec![Sexpr::sym("Row"), mode_expr_to_sexpr(inner)]),
        ModeExpr::Opaque(inner) => {
            Sexpr::list(vec![Sexpr::sym("opaque"), mode_expr_to_sexpr(inner)])
        }
        ModeExpr::Enum(names) => {
            let syms: Vec<Sexpr> = names.iter().map(|n| Sexpr::sym(&n.text)).collect();
            Sexpr::list(vec![Sexpr::sym("enum"), Sexpr::list(syms)])
        }
        ModeExpr::Union(variants) => {
            let pairs: Vec<Sexpr> = variants
                .iter()
                .map(|(tag, mode)| {
                    Sexpr::list(vec![Sexpr::sym(&tag.text), mode_expr_to_sexpr(mode)])
                })
                .collect();
            Sexpr::list(vec![Sexpr::sym("variant"), Sexpr::list(pairs)])
        }
        ModeExpr::Struct(fields) => {
            let mut field_pairs = Vec::new();
            for field in fields {
                let name = &field.name.text;
                let mode = mode_expr_to_sexpr(&field.mode);
                field_pairs.push(Sexpr::list(vec![Sexpr::sym(name), mode]));
            }
            Sexpr::list(vec![Sexpr::sym("record"), Sexpr::list(field_pairs)])
        }
    }
}

fn pred_to_sexpr(pred: &Pred) -> Sexpr {
    match pred {
        Pred::Cmp { op, lhs, rhs } => {
            let op_str = match op {
                CmpOp::Eq => "=",
                CmpOp::Lt => "<",
                CmpOp::Le => "<=",
            };
            Sexpr::list(vec![
                Sexpr::sym(op_str),
                expr_to_sexpr(lhs),
                expr_to_sexpr(rhs),
            ])
        }
        Pred::And(a, b) => Sexpr::list(vec![Sexpr::sym("and"), pred_to_sexpr(a), pred_to_sexpr(b)]),
        Pred::Or(a, b) => Sexpr::list(vec![Sexpr::sym("or"), pred_to_sexpr(a), pred_to_sexpr(b)]),
        Pred::Not(p) => Sexpr::list(vec![Sexpr::sym("not"), pred_to_sexpr(p)]),
        Pred::ForAll { mode, var, body } => Sexpr::list(vec![
            Sexpr::sym("forall"),
            Sexpr::list(vec![Sexpr::list(vec![
                Sexpr::sym(&var.text),
                Sexpr::sym(&mode.text),
            ])]),
            pred_to_sexpr(body),
        ]),
        Pred::Exists { mode, var, body } => Sexpr::list(vec![
            Sexpr::sym("exists"),
            Sexpr::list(vec![Sexpr::list(vec![
                Sexpr::sym(&var.text),
                Sexpr::sym(&mode.text),
            ])]),
            pred_to_sexpr(body),
        ]),
        Pred::Call { name, args } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            for arg in args {
                items.push(expr_to_sexpr(arg));
            }
            Sexpr::list(items)
        }
        Pred::Word(w) => Sexpr::sym(&w.text),
    }
}

fn expr_to_sexpr(expr: &Expr) -> Sexpr {
    match expr {
        Expr::Int(i) => Sexpr::Int(*i),
        Expr::Str(s) => Sexpr::Str(s.clone()),
        Expr::Path(segs) => {
            let path_str = segs
                .iter()
                .map(|s| s.text.clone())
                .collect::<Vec<_>>()
                .join("/");
            Sexpr::sym(&path_str)
        }
        Expr::Call { name, args } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            for arg in args {
                items.push(expr_to_sexpr(arg));
            }
            Sexpr::list(items)
        }
    }
}

/// The source span of a declaration, for elaboration diagnostics.
fn decl_span(decl: &Decl) -> crate::span::Span {
    match decl {
        Decl::Use(d) => d.span,
        Decl::Application(d) => d.span,
        Decl::Actor(d) => d.span,
        Decl::Mode(d) => d.span,
        Decl::Component(d) => d.span,
        Decl::Interface(d) => d.span,
        Decl::State(d) => d.span,
        Decl::Flow(d) => d.span,
        Decl::Behavior(d) => d.span,
        Decl::Invariant(d) => d.span,
        Decl::Constraint(d) => d.span,
        Decl::Synthesis(d) => d.span,
        Decl::Acceptance(d) => d.span,
    }
}

/// The single canonical diagnostic Sexpr shape:
/// (diagnostic (severity s) (code "C") (span a b) (message "...")).
fn diag_sexpr(severity: &str, code: &str, span: (i64, i64), message: String) -> Sexpr {
    Sexpr::list(vec![
        Sexpr::sym("diagnostic"),
        Sexpr::list(vec![Sexpr::sym("severity"), Sexpr::sym(severity)]),
        Sexpr::list(vec![Sexpr::sym("code"), Sexpr::Str(code.to_string())]),
        Sexpr::list(vec![
            Sexpr::sym("span"),
            Sexpr::Int(span.0),
            Sexpr::Int(span.1),
        ]),
        Sexpr::list(vec![Sexpr::sym("message"), Sexpr::Str(message)]),
    ])
}

fn lower_diagnostics(diags: &[Diagnostic]) -> Vec<Sexpr> {
    let mut result = Vec::new();
    for diag in diags {
        let severity_str = match diag.severity {
            Severity::Error => "error",
            Severity::Warning => "warning",
        };
        let diag_sexpr = diag_sexpr(
            severity_str,
            diag.code,
            (diag.span.start as i64, diag.span.end as i64),
            diag.message.clone(),
        );
        result.push(diag_sexpr);
    }
    result
}
