use crate::ast::*;
use crate::check;
use crate::diag::{Diagnostic, Severity};
use crate::ir::{Ir, IrNode};
use crate::profile;
use crate::sexpr::Sexpr;
use std::collections::{HashMap, HashSet};

/// Elaborate a parsed file: expand profiles, check, lower to IR.
/// Diagnostics from checking and elaboration are folded into the IR;
/// the caller inspects Ir::has_errors().
pub fn elaborate(file: &File) -> Ir {
    elaborate_with_parse_diags(file, &[]).0
}

/// Elaborate with the parser's diagnostics folded in, so the serialized
/// IR is self-describing even for a spec that only partially parsed.
/// Returns the IR and the full typed diagnostic list (parse, then check,
/// then elaboration) for terminal rendering.
pub fn elaborate_with_parse_diags(
    file: &File,
    parse_diags: &[Diagnostic],
) -> (Ir, Vec<Diagnostic>) {
    let mut elaborator = Elaborator::new(&file.spec.name.text);

    // Step 0 (v0.2): the constant registry — spec `const` declarations
    // plus every integer parameter of every RESOLVED `use` profile
    // (`sharing_limit 256` binds `sharing_limit` = 256). Duplicates in
    // any combination are E201, the standard duplicate shape.
    elaborator.build_const_registry(&file.decls);

    // Step 1: Profile expansion. Each entry carries the profile name it
    // was generated by (None for declarations written in the source).
    let expanded_decls = elaborator.expand_profiles(&file.decls);

    // Step 1b (post-gate-10, finding 1): E211 constant-name collisions,
    // checked over the EXPANDED declarations so profile-generated
    // behaviors are covered too.
    let expanded_only: Vec<Decl> = expanded_decls.iter().map(|(d, _)| d.clone()).collect();
    elaborator.check_const_collisions(&expanded_only);
    let mut all_diags: Vec<Diagnostic> = parse_diags.to_vec();

    // Step 2: Check the expanded declarations
    let temp_file = File {
        spec: file.spec.clone(),
        decls: expanded_decls.iter().map(|(d, _)| d.clone()).collect(),
    };
    let check_diags = check::check(&temp_file);
    all_diags.extend(check_diags);

    // Step 3: Lower all declarations; profile-generated nodes carry a
    // :profile-source field so provenance survives into the IR.
    let mut all_nodes = Vec::new();
    let mut node_spans = Vec::new();
    for (decl, source) in &expanded_decls {
        if let Some(node) = elaborator.lower_decl(decl) {
            // v0.2 substitution pass: constant references become the
            // literal values (E209 where a constants-only position names
            // no constant) BEFORE provenance annotation, so a
            // const-spelled spec and its literal-spelled twin carry
            // byte-identical nodes.
            let node = elaborator.substitute_node(node, decl_span(decl));
            let node = match source {
                Some(profile_name) => {
                    let mut fields = node.fields.clone();
                    fields.push((":profile-source".to_string(), Sexpr::sym(profile_name)));
                    IrNode::new(node.id, &node.kind, node.name, fields, node.clauses)
                }
                None => node,
            };
            all_nodes.push(node);
            node_spans.push(decl_span(decl));
        }
    }

    // Step 4: elaboration diagnostics — profile expansion first, then
    // duplicate semantic IDs (span pointing at the duplicate declaration).
    all_diags.extend(elaborator.elab_diags.iter().cloned());
    let mut seen_ids = HashSet::new();
    for (node, span) in all_nodes.iter().zip(node_spans.iter()) {
        if !seen_ids.insert(&node.id) {
            all_diags.push(Diagnostic {
                severity: Severity::Error,
                code: "E301",
                span: *span,
                message: format!("duplicate-semantic-id: {}", node.id),
            });
        }
    }
    let ir_diags = lower_diagnostics(&all_diags);

    // Step 5: Partition nodes by kind
    let mut design = Vec::new();
    let mut transitions = Vec::new();
    let mut obligations = Vec::new();
    let mut synthesis = Vec::new();

    for node in all_nodes {
        match node.kind.as_str() {
            "import" | "application" | "actor" | "type" | "component" | "interface" | "state"
            | "flow" => design.push(node),
            "behavior" => transitions.push(node),
            "invariant" | "constraint" | "acceptance" => obligations.push(node),
            "synthesis" => synthesis.push(node),
            _ => {
                // Unknown kind - shouldn't happen if lowering is correct
                design.push(node);
            }
        }
    }

    // Module fields come from the spec header.
    let mut module_fields = vec![
        (
            ":exports".to_string(),
            Sexpr::list(
                file.spec
                    .exports
                    .iter()
                    .map(|e| Sexpr::sym(&e.text))
                    .collect(),
            ),
        ),
        (":owner".to_string(), Sexpr::sym(&file.spec.owner.text)),
        (
            ":version".to_string(),
            Sexpr::Str(file.spec.version.clone()),
        ),
    ];
    // v0.2: the constants header — `(:constants ((name value source)
    // ...))`, sorted by name, source `spec` or the profile name string.
    // Present only when at least one constant is bound, and
    // fingerprinted like every other header field, so the binding
    // survives into provenance.
    if let Some(header) = elaborator.constants_header() {
        module_fields.push((":constants".to_string(), header));
    }

    // Build IR with partitioning and sorting
    let ir = Ir::new(
        "gymnast.ir/0.1".to_string(),
        elaborator.module_name.clone(),
        module_fields,
        design,
        transitions,
        obligations,
        synthesis,
        ir_diags,
    );

    (ir, all_diags)
}

/// One bound constant (v0.2): name, integer value, and provenance —
/// `Sexpr::sym("spec")` for a spec-level `const`, the profile name as a
/// string for a `use` parameter binding.
struct ConstBinding {
    name: String,
    value: i64,
    source: Sexpr,
    span: crate::span::Span,
}

struct Elaborator {
    module_name: String,
    elab_diags: Vec<Diagnostic>,
    consts: Vec<ConstBinding>,
}

impl Elaborator {
    fn new(module_name: &str) -> Self {
        Elaborator {
            module_name: module_name.to_string(),
            elab_diags: Vec::new(),
            consts: Vec::new(),
        }
    }

    // -- v0.2 constant registry ------------------------------------------

    /// Binds spec `const` declarations and every INTEGER parameter of
    /// every resolvable `use` profile, in declaration order. Non-integer
    /// profile parameters (e.g. `identity_provider google`) are not
    /// constants in v0.2 and bind nothing.
    fn build_const_registry(&mut self, decls: &[Decl]) {
        for decl in decls {
            match decl {
                Decl::Const(c) => {
                    self.bind_const(&c.name.text, c.value, Sexpr::sym("spec"), c.name.span);
                }
                Decl::Use(u) => {
                    let profile_name = u
                        .path
                        .iter()
                        .map(|i| i.text.clone())
                        .collect::<Vec<_>>()
                        .join("/");
                    let Some(profile) = crate::profile::lookup(&profile_name, &u.version) else {
                        continue;
                    };
                    for item in &u.args {
                        if let PackValue::Int(v) = item.value {
                            // Post-gate-10 (gate finding 8): only a
                            // parameter the profile DECLARES may bind a
                            // profile-attributed constant; an undeclared
                            // integer argument (typo'd or invented) binds
                            // nothing and warns W411, so the header never
                            // attributes to a profile a binding it does
                            // not define.
                            if !profile.params.iter().any(|p| p.key == item.key.text) {
                                self.elab_diags.push(Diagnostic {
                                    severity: Severity::Warning,
                                    code: "W411",
                                    span: item.span,
                                    message: format!(
                                        "undeclared-profile-parameter: '{}' is not a \
                                         parameter of profile '{}'; it binds no constant",
                                        item.key.text, profile_name
                                    ),
                                });
                                continue;
                            }
                            self.bind_const(
                                &item.key.text,
                                v,
                                Sexpr::Str(profile_name.clone()),
                                item.span,
                            );
                        }
                    }
                }
                _ => {}
            }
        }
    }

    fn bind_const(&mut self, name: &str, value: i64, source: Sexpr, span: crate::span::Span) {
        if self.consts.iter().any(|c| c.name == name) {
            self.elab_diags.push(Diagnostic {
                severity: Severity::Error,
                code: "E201",
                span,
                message: format!(
                    "duplicate constant name '{}' (already bound by an \
                     earlier const declaration or profile parameter)",
                    name
                ),
            });
            return;
        }
        self.consts.push(ConstBinding {
            name: name.to_string(),
            value,
            source,
            span,
        });
    }

    /// Post-gate-10 collision guard (gate finding 1): NAME-DRIVEN
    /// substitution rewrites ANY matching symbol in an operand
    /// position, so a constant whose name equals an author-declared
    /// variable — a behavior parameter, an acceptance generator
    /// variable, a scenario `given` variable — or one of the reserved
    /// state symbols `pre`/`post`/`result` would silently rewrite that
    /// variable (including inside authority predicates). E211 makes the
    /// collision an error at the binding site instead.
    fn check_const_collisions(&mut self, decls: &[Decl]) {
        if self.consts.is_empty() {
            return;
        }
        // name -> what it collides with, first occurrence wins.
        let mut targets: Vec<(String, String)> = vec![
            ("pre".into(), "the reserved state symbol `pre`".into()),
            ("post".into(), "the reserved state symbol `post`".into()),
            ("result".into(), "the reserved state symbol `result`".into()),
        ];
        let add = |name: &str, desc: String, targets: &mut Vec<(String, String)>| {
            if !targets.iter().any(|(n, _)| n == name) {
                targets.push((name.to_string(), desc));
            }
        };
        for decl in decls {
            match decl {
                Decl::Behavior(b) => {
                    for binder in &b.binders {
                        add(
                            &binder.text,
                            format!("a parameter of behavior '{}'", b.name.text),
                            &mut targets,
                        );
                    }
                }
                Decl::Acceptance(acc) => {
                    for block in &acc.blocks {
                        match block {
                            AcceptanceBlock::Property { name, body } => {
                                for item in body {
                                    if item.key.text != "generate" {
                                        continue;
                                    }
                                    if let PackValue::Nested(pairs) = &item.value {
                                        for pair in pairs {
                                            add(
                                                &pair.key.text,
                                                format!(
                                                    "a generator variable of property '{}'",
                                                    name.text
                                                ),
                                                &mut targets,
                                            );
                                        }
                                    }
                                }
                            }
                            AcceptanceBlock::Scenario { name, steps } => {
                                for item in steps {
                                    if item.key.text != "given" {
                                        continue;
                                    }
                                    if let PackValue::Nested(pairs) = &item.value {
                                        for pair in pairs {
                                            add(
                                                &pair.key.text,
                                                format!(
                                                    "a `given` variable of scenario '{}'",
                                                    name.text
                                                ),
                                                &mut targets,
                                            );
                                        }
                                    }
                                }
                            }
                            _ => {}
                        }
                    }
                }
                _ => {}
            }
        }
        let collisions: Vec<(String, String, crate::span::Span)> = self
            .consts
            .iter()
            .filter_map(|c| {
                targets
                    .iter()
                    .find(|(n, _)| *n == c.name)
                    .map(|(_, desc)| (c.name.clone(), desc.clone(), c.span))
            })
            .collect();
        for (name, desc, span) in collisions {
            self.elab_diags.push(Diagnostic {
                severity: Severity::Error,
                code: "E211",
                span,
                message: format!(
                    "constant-name-collision: constant '{}' collides with {}; \
                     substitution would silently rewrite it — rename one",
                    name, desc
                ),
            });
        }
    }

    fn const_value(&self, name: &str) -> Option<i64> {
        self.consts.iter().find(|c| c.name == name).map(|c| c.value)
    }

    /// The `:constants` module-field value: `((name value source) ...)`
    /// sorted by name. `None` when no constant is bound.
    fn constants_header(&self) -> Option<Sexpr> {
        if self.consts.is_empty() {
            return None;
        }
        let mut sorted: Vec<&ConstBinding> = self.consts.iter().collect();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));
        Some(Sexpr::List(
            sorted
                .into_iter()
                .map(|c| {
                    Sexpr::List(vec![
                        Sexpr::sym(&c.name),
                        Sexpr::Int(c.value),
                        c.source.clone(),
                    ])
                })
                .collect(),
        ))
    }

    // -- v0.2 substitution pass ------------------------------------------
    //
    // Substitution is NAME-DRIVEN over the plan's reference positions —
    // predicate operands, property execute / scenario `when` step
    // arguments, refinement bounds, workload `under` values — and total
    // there: any Sym naming a bound constant becomes its Int, and the
    // call-shaped offset forms `(+ name N)` / `(- name N)` become
    // Int(value ± N). E209 (`unresolved-constant`) fires ONLY for the
    // explicitly-const-shaped forms: an offset form whose name resolves
    // to nothing (anywhere), and a bare IDENT in a refinement bound or
    // `under` value (positions where only constants are legal). Bare
    // unknown atoms in predicate positions stay what they are today:
    // abstract predicates. Names OUTSIDE the reference positions —
    // clause heads, error names, `:errors` sets, generator symbols,
    // field names, emitted event names, the import node's `:arguments`
    // provenance — are never substituted.

    fn e209(&mut self, name: &str, span: crate::span::Span) {
        self.elab_diags.push(Diagnostic {
            severity: Severity::Error,
            code: "E209",
            span,
            message: format!("unresolved-constant: '{}' names no declared constant", name),
        });
    }

    /// Applies the substitution pass to one freshly lowered node. The
    /// pass always runs (E209's constants-only positions must be
    /// diagnosed even in a spec with no constants at all); with an empty
    /// registry and no const-shaped forms it rebuilds the node
    /// byte-identically.
    fn substitute_node(&mut self, node: IrNode, span: crate::span::Span) -> IrNode {
        match node.kind.as_str() {
            // The import node's `:arguments` record is provenance — the
            // one place a constant's own (name value) pair lives — and
            // is deliberately not scanned.
            "import" => node,
            "behavior" => {
                let clauses = node
                    .clauses
                    .iter()
                    .map(|c| self.subst_behavior_clause(c, span))
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, node.fields, clauses)
            }
            "invariant" => {
                let fields = node
                    .fields
                    .iter()
                    .map(|(k, v)| {
                        if k == ":always" {
                            (k.clone(), self.subst_operand(v, span))
                        } else {
                            (k.clone(), v.clone())
                        }
                    })
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, fields, node.clauses)
            }
            "constraint" => {
                let fields = node
                    .fields
                    .iter()
                    .map(|(k, v)| match k.as_str() {
                        ":must" => (k.clone(), self.subst_operand(v, span)),
                        ":under" => (k.clone(), self.subst_under(v, span)),
                        _ => (k.clone(), v.clone()),
                    })
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, fields, node.clauses)
            }
            "acceptance" => {
                let clauses = node
                    .clauses
                    .iter()
                    .map(|c| self.subst_acceptance_clause(c, span))
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, node.fields, clauses)
            }
            "type" => {
                let fields = node
                    .fields
                    .iter()
                    .map(|(k, v)| (k.clone(), self.subst_bounds(v, span)))
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, fields, node.clauses)
            }
            "interface" => {
                let clauses = node
                    .clauses
                    .iter()
                    .map(|c| self.subst_bounds(c, span))
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, node.fields, clauses)
            }
            // Post-gate-10 (gate finding 2): the synthesis budget slots
            // are constants-only integer positions — `:attempts` and the
            // model pack's `max_attempts` value. Every other synthesis
            // field (target, platform, model name/class, must_not) is a
            // name and is never substituted.
            "synthesis" => {
                let fields = node
                    .fields
                    .iter()
                    .map(|(k, v)| match k.as_str() {
                        ":attempts" => (k.clone(), self.subst_under_value(v, span)),
                        ":model" => (k.clone(), self.subst_model_pack(v, span)),
                        _ => (k.clone(), v.clone()),
                    })
                    .collect();
                IrNode::new(node.id, &node.kind, node.name, fields, node.clauses)
            }
            _ => node,
        }
    }

    /// The synthesis `:model` value, `(name ((key value) ...))`: only
    /// the `max_attempts` pair's value slot is a constants-only integer
    /// position; the model name and every other attribute are kept.
    fn subst_model_pack(&mut self, model: &Sexpr, span: crate::span::Span) -> Sexpr {
        let Some(items) = model.as_list() else {
            return model.clone();
        };
        if items.len() != 2 {
            return model.clone();
        }
        let Some(pairs) = items[1].as_list() else {
            return model.clone();
        };
        let new_pairs: Vec<Sexpr> = pairs
            .iter()
            .map(|pair| {
                let Some(kv) = pair.as_list() else {
                    return pair.clone();
                };
                if kv.len() == 2 && kv[0].as_sym() == Some("max_attempts") {
                    Sexpr::List(vec![kv[0].clone(), self.subst_under_value(&kv[1], span)])
                } else {
                    pair.clone()
                }
            })
            .collect();
        Sexpr::List(vec![items[0].clone(), Sexpr::List(new_pairs)])
    }

    /// The offset forms `(+ name N)` / `(- name N)`: `Some(replacement)`
    /// when `items` is offset-shaped (an unresolved name keeps the
    /// original form and records the E209); `None` when it is not.
    fn try_offset(&mut self, items: &[Sexpr], span: crate::span::Span) -> Option<Sexpr> {
        if items.len() != 3 {
            return None;
        }
        let op = items[0].as_sym()?;
        if op != "+" && op != "-" {
            return None;
        }
        let name = items[1].as_sym()?.to_string();
        let n = items[2].as_int()?;
        Some(match self.const_value(&name) {
            Some(v) => Sexpr::Int(if op == "+" {
                v.saturating_add(n)
            } else {
                v.saturating_sub(n)
            }),
            None => {
                self.e209(&name, span);
                Sexpr::List(items.to_vec())
            }
        })
    }

    /// Substitution over a predicate / step / expression operand tree.
    /// List heads (operators, predicate and operation names) are kept;
    /// quantifier binder lists are kept; everything in operand position
    /// is substituted recursively.
    fn subst_operand(&mut self, s: &Sexpr, span: crate::span::Span) -> Sexpr {
        match s {
            Sexpr::Sym(n) => match self.const_value(n) {
                Some(v) => Sexpr::Int(v),
                None => s.clone(),
            },
            Sexpr::List(items) => {
                if let Some(replaced) = self.try_offset(items, span) {
                    return replaced;
                }
                let head = items.first().and_then(|h| h.as_sym());
                if head == Some("forall") || head == Some("exists") {
                    let mut out = Vec::with_capacity(items.len());
                    out.push(items[0].clone());
                    if items.len() > 1 {
                        out.push(items[1].clone());
                    }
                    for item in items.iter().skip(2) {
                        out.push(self.subst_operand(item, span));
                    }
                    return Sexpr::List(out);
                }
                let mut out = Vec::with_capacity(items.len());
                for (i, item) in items.iter().enumerate() {
                    if i == 0 && item.as_sym().is_some() {
                        out.push(item.clone());
                    } else {
                        out.push(self.subst_operand(item, span));
                    }
                }
                Sexpr::List(out)
            }
            _ => s.clone(),
        }
    }

    /// Behavior clauses: `requires`/`ensures`/`returns` tails and the
    /// `fails` clause's `:when` value are operand positions; the error
    /// name, `:preserves` target, and `emits` clauses are not.
    fn subst_behavior_clause(&mut self, clause: &Sexpr, span: crate::span::Span) -> Sexpr {
        let Some(items) = clause.as_list() else {
            return clause.clone();
        };
        match items.first().and_then(|h| h.as_sym()) {
            Some("requires") | Some("ensures") | Some("returns") => {
                let mut out = vec![items[0].clone()];
                for item in items.iter().skip(1) {
                    out.push(self.subst_operand(item, span));
                }
                Sexpr::List(out)
            }
            Some("fails") => self.subst_after_markers(items, &[":when"], span),
            _ => clause.clone(),
        }
    }

    /// Rebuilds a keyword-shaped clause, substituting only the value
    /// following each marker in `markers`.
    fn subst_after_markers(
        &mut self,
        items: &[Sexpr],
        markers: &[&str],
        span: crate::span::Span,
    ) -> Sexpr {
        let mut out = Vec::with_capacity(items.len());
        let mut i = 0;
        while i < items.len() {
            let is_marker = items[i]
                .as_sym()
                .map(|s| markers.contains(&s))
                .unwrap_or(false);
            if is_marker && i + 1 < items.len() {
                out.push(items[i].clone());
                out.push(self.subst_operand(&items[i + 1], span));
                i += 2;
            } else {
                out.push(items[i].clone());
                i += 1;
            }
        }
        Sexpr::List(out)
    }

    /// Acceptance clauses: property `:execute` steps and `:must`
    /// assertions, scenario `when` step values, and concurrency/fault
    /// `:must` assertions are operand positions. `:generate` pairs,
    /// scenario `given`/`then` values, fault `:after`/`:inject` names,
    /// and the coverage/execution clauses are not.
    fn subst_acceptance_clause(&mut self, clause: &Sexpr, span: crate::span::Span) -> Sexpr {
        let Some(items) = clause.as_list() else {
            return clause.clone();
        };
        match items.first().and_then(|h| h.as_sym()) {
            Some("property") => self.subst_after_markers(items, &[":execute", ":must"], span),
            Some("concurrency") => {
                // Post-gate-10 (gate finding 2): `:actors` is a
                // constants-only integer position, same rules as a
                // workload `under` value; `:schedule` is a name.
                let with_must = self.subst_after_markers(items, &[":must"], span);
                let Some(after) = with_must.as_list() else {
                    return with_must;
                };
                let mut out = Vec::with_capacity(after.len());
                let mut i = 0;
                while i < after.len() {
                    if after[i].as_sym() == Some(":actors") && i + 1 < after.len() {
                        out.push(after[i].clone());
                        out.push(self.subst_under_value(&after[i + 1], span));
                        i += 2;
                    } else {
                        out.push(after[i].clone());
                        i += 1;
                    }
                }
                Sexpr::List(out)
            }
            Some("fault") => self.subst_after_markers(items, &[":must"], span),
            Some("scenario") => {
                let mut out = Vec::with_capacity(items.len());
                for item in items {
                    let is_when_step = item
                        .as_list()
                        .map(|step| step.len() == 2 && step[0].as_sym() == Some("when"))
                        .unwrap_or(false);
                    if is_when_step {
                        let step = item.as_list().expect("checked above");
                        out.push(Sexpr::List(vec![
                            step[0].clone(),
                            self.subst_operand(&step[1], span),
                        ]));
                    } else {
                        out.push(item.clone());
                    }
                }
                Sexpr::List(out)
            }
            _ => clause.clone(),
        }
    }

    /// Workload `under` values are constants-only integer positions: a
    /// bare IDENT resolves or is E209; the `(name unit)` form (a
    /// constant with a duration unit, e.g. `duration dur min`) resolves
    /// to the canonical `(unit value)` quantity pair or is E209;
    /// anything else takes the generic operand rules (which handle the
    /// offset forms).
    fn subst_under(&mut self, under: &Sexpr, span: crate::span::Span) -> Sexpr {
        let Some(pairs) = under.as_list() else {
            return under.clone();
        };
        Sexpr::List(
            pairs
                .iter()
                .map(|pair| {
                    let Some(kv) = pair.as_list() else {
                        return pair.clone();
                    };
                    if kv.len() != 2 {
                        return pair.clone();
                    }
                    let new_value = self.subst_under_value(&kv[1], span);
                    Sexpr::List(vec![kv[0].clone(), new_value])
                })
                .collect(),
        )
    }

    fn subst_under_value(&mut self, value: &Sexpr, span: crate::span::Span) -> Sexpr {
        match value {
            Sexpr::Sym(n) => match self.const_value(n) {
                Some(v) => Sexpr::Int(v),
                None => {
                    let name = n.clone();
                    self.e209(&name, span);
                    value.clone()
                }
            },
            Sexpr::List(items) if items.len() == 2 => {
                if let (Sexpr::Sym(name), Sexpr::Sym(unit)) = (&items[0], &items[1]) {
                    if is_duration_unit(unit) {
                        let name = name.clone();
                        let unit = unit.clone();
                        return match self.const_value(&name) {
                            Some(v) => Sexpr::List(vec![Sexpr::Sym(unit), Sexpr::Int(v)]),
                            None => {
                                self.e209(&name, span);
                                value.clone()
                            }
                        };
                    }
                }
                self.subst_operand(value, span)
            }
            _ => self.subst_operand(value, span),
        }
    }

    /// Mode-shape substitution: ONLY the value slot after a `:min`/
    /// `:max` marker is an integer position (refinement bounds); every
    /// other symbol in a type shape (field names, enum members, error
    /// sets on interface ops) is a name, never a constant reference.
    fn subst_bounds(&mut self, s: &Sexpr, span: crate::span::Span) -> Sexpr {
        let Some(items) = s.as_list() else {
            return s.clone();
        };
        let mut out: Vec<Sexpr> = items
            .iter()
            .map(|item| self.subst_bounds(item, span))
            .collect();
        let mut i = 0;
        while i + 1 < out.len() {
            let is_bound_marker = matches!(out[i].as_sym(), Some(":min") | Some(":max"));
            if is_bound_marker {
                if let Sexpr::Sym(n) = &out[i + 1] {
                    let name = n.clone();
                    match self.const_value(&name) {
                        Some(v) => out[i + 1] = Sexpr::Int(v),
                        None => self.e209(&name, span),
                    }
                }
                i += 2;
            } else {
                i += 1;
            }
        }
        Sexpr::List(out)
    }

    fn expand_profiles(&mut self, decls: &[Decl]) -> Vec<(Decl, Option<String>)> {
        let mut expanded = Vec::new();

        for decl in decls {
            expanded.push((decl.clone(), None));

            // If this is a Use declaration, try to expand it
            if let Decl::Use(use_decl) = decl {
                let profile_name = use_decl
                    .path
                    .iter()
                    .map(|i| i.text.clone())
                    .collect::<Vec<_>>()
                    .join("/");
                let profile_version = use_decl.version.clone();

                match profile::lookup(&profile_name, &profile_version) {
                    Some(prof) => {
                        // Validate required parameters
                        let mut args_map: HashMap<String, Sexpr> = HashMap::new();
                        for item in &use_decl.args {
                            let key = item.key.text.clone();
                            let value = pack_value_to_sexpr(&item.value);
                            args_map.insert(key, value);
                        }

                        let mut missing_required = false;
                        for param in &prof.params {
                            if matches!(param.default, profile::ParamDefault::Required) {
                                if !args_map.contains_key(param.key) {
                                    self.elab_diags.push(Diagnostic {
                                        severity: Severity::Error,
                                        code: "E302",
                                        span: use_decl.span,
                                        message: format!(
                                            "missing-profile-decision: {} required",
                                            param.key
                                        ),
                                    });
                                    missing_required = true;
                                }
                            }
                        }

                        // If no missing required params, generate declarations.
                        // Arguments are handed to the generator in declared
                        // parameter order — never HashMap order — so
                        // expansion stays deterministic.
                        if !missing_required {
                            let args_vec: Vec<(String, Sexpr)> = prof
                                .params
                                .iter()
                                .filter_map(|p| {
                                    args_map.get(p.key).map(|v| (p.key.to_string(), v.clone()))
                                })
                                .collect();
                            let generated = (prof.generate)(&args_vec);
                            for gen_decl in generated {
                                expanded.push((gen_decl, Some(profile_name.clone())));
                            }
                        }
                    }
                    None => {
                        self.elab_diags.push(Diagnostic {
                            severity: Severity::Warning,
                            code: "W303",
                            span: use_decl.span,
                            message: format!("unknown-profile: {}", profile_name),
                        });
                    }
                }
            }
        }

        expanded
    }

    fn lower_decl(&self, decl: &Decl) -> Option<IrNode> {
        match decl {
            Decl::Use(use_decl) => self.lower_use(use_decl),
            // A const declaration produces NO IR node: its record is the
            // module's `:constants` header entry, and every reference
            // site carries the substituted literal (v0.2 — a
            // const-spelled spec and its literal-spelled twin lower to
            // identical node lists).
            Decl::Const(_) => None,
            Decl::Application(app) => self.lower_application(app),
            Decl::Actor(actor) => self.lower_actor(actor),
            Decl::Mode(mode) => self.lower_mode(mode),
            Decl::Component(comp) => self.lower_component(comp),
            Decl::Interface(iface) => self.lower_interface(iface),
            Decl::State(state) => self.lower_state(state),
            Decl::Flow(flow) => self.lower_flow(flow),
            Decl::Behavior(behavior) => self.lower_behavior(behavior),
            Decl::Invariant(inv) => self.lower_invariant(inv),
            Decl::Constraint(constr) => self.lower_constraint(constr),
            Decl::Synthesis(synth) => self.lower_synthesis(synth),
            Decl::Acceptance(acc) => self.lower_acceptance(acc),
        }
    }

    fn lower_use(&self, use_decl: &UseDecl) -> Option<IrNode> {
        let mut fields = vec![(":version".to_string(), Sexpr::Str(use_decl.version.clone()))];

        // Arguments as nested list
        let mut args_list = Vec::new();
        for item in &use_decl.args {
            let key = item.key.text.clone();
            let value = pack_value_to_sexpr(&item.value);
            args_list.push(Sexpr::list(vec![Sexpr::sym(&key), value]));
        }
        fields.push((":arguments".to_string(), Sexpr::list(args_list)));

        fields.push((":authority".to_string(), Sexpr::sym("authoritative")));

        let id = format!(
            "{}/import/{}",
            self.module_name,
            use_decl
                .path
                .iter()
                .map(|i| i.text.clone())
                .collect::<Vec<_>>()
                .join("/")
        );
        let name = use_decl
            .path
            .iter()
            .map(|i| i.text.clone())
            .collect::<Vec<_>>()
            .join("/");

        Some(IrNode::new(id, "import", name, fields, vec![]))
    }

    fn lower_application(&self, app: &ApplicationDecl) -> Option<IrNode> {
        let fields = pack_to_fields(&app.attrs);
        let id = format!("{}/application/{}", self.module_name, app.name.text);

        Some(IrNode::new(
            id,
            "application",
            app.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_actor(&self, actor: &ActorDecl) -> Option<IrNode> {
        let mut fields = vec![(":kind".to_string(), Sexpr::sym(&actor.kind.text))];
        fields.extend(pack_to_fields(&actor.attrs));
        let id = format!("{}/actor/{}", self.module_name, actor.name.text);

        Some(IrNode::new(
            id,
            "actor",
            actor.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_mode(&self, mode: &ModeDecl) -> Option<IrNode> {
        let mode_fields = mode_expr_to_shape_field(&mode.expr);
        let fields = vec![mode_fields];
        let id = format!("{}/type/{}", self.module_name, mode.name.text);

        Some(IrNode::new(
            id,
            "type",
            mode.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_component(&self, comp: &ComponentDecl) -> Option<IrNode> {
        let fields = pack_to_fields(&comp.attrs);
        let id = format!("{}/component/{}", self.module_name, comp.name.text);

        Some(IrNode::new(
            id,
            "component",
            comp.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_interface(&self, iface: &InterfaceDecl) -> Option<IrNode> {
        let fields = vec![(":for".to_string(), Sexpr::sym(&iface.default_actor.text))];

        let mut clauses = Vec::new();
        for op in &iface.ops {
            let clause = self.lower_op_to_clause(op, &iface.default_actor.text);
            clauses.push(clause);
        }

        let id = format!("{}/interface/{}", self.module_name, iface.name.text);

        Some(IrNode::new(
            id,
            "interface",
            iface.name.text.clone(),
            fields,
            clauses,
        ))
    }

    fn lower_op_to_clause(&self, op: &OpDecl, default_actor: &str) -> Sexpr {
        let head = match op.kind {
            OpKind::Cmd => "command",
            OpKind::Qry => "query",
        };

        let mut items = vec![
            Sexpr::sym(head),
            Sexpr::sym(&op.name.text),
            Sexpr::sym(":actor"),
            Sexpr::sym(default_actor),
        ];

        // Input: record of params
        let mut param_pairs = Vec::new();
        for param in &op.params {
            let mode_sexpr = mode_expr_to_sexpr(&param.mode);
            param_pairs.push(Sexpr::list(vec![Sexpr::sym(&param.name.text), mode_sexpr]));
        }
        items.push(Sexpr::sym(":input"));
        items.push(Sexpr::list(vec![
            Sexpr::sym("record"),
            Sexpr::list(param_pairs),
        ]));

        // Output
        items.push(Sexpr::sym(":output"));
        items.push(mode_expr_to_sexpr(&op.output));

        // Errors
        items.push(Sexpr::sym(":errors"));
        let error_syms: Vec<Sexpr> = op.errors.iter().map(|e| Sexpr::sym(&e.text)).collect();
        items.push(Sexpr::list(error_syms));

        Sexpr::list(items)
    }

    fn lower_state(&self, state: &StateDecl) -> Option<IrNode> {
        let fields = pack_to_fields(&state.attrs);
        let id = format!("{}/state/{}", self.module_name, state.name.text);

        Some(IrNode::new(
            id,
            "state",
            state.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_flow(&self, flow: &FlowDecl) -> Option<IrNode> {
        // Normalize the flow kind to the same vocabulary interface op
        // clauses use, so one concept has one spelling in the IR.
        let kind = match flow.kind.text.as_str() {
            "cmd" => "command",
            "qry" => "query",
            other => other,
        };
        let mut fields = vec![
            (":from".to_string(), Sexpr::sym(&flow.from.text)),
            (":to".to_string(), Sexpr::sym(&flow.to.text)),
            (":kind".to_string(), Sexpr::sym(kind)),
        ];
        fields.extend(pack_to_fields(&flow.attrs));
        let id = format!("{}/flow/{}", self.module_name, flow.name.text);

        Some(IrNode::new(
            id,
            "flow",
            flow.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_behavior(&self, behavior: &BehaviorDecl) -> Option<IrNode> {
        // :on = (interface/op binder...) with EVERY declared binder — the
        // binder list is the spec author's, never truncated or defaulted.
        let mut on_items = vec![Sexpr::sym(&format!(
            "{}/{}",
            behavior.on_interface.text, behavior.on_op.text
        ))];
        for binder in &behavior.binders {
            on_items.push(Sexpr::sym(&binder.text));
        }
        let on_value = Sexpr::list(on_items);

        let mut fields = vec![(":on".to_string(), on_value)];
        fields.extend(pack_to_fields(&behavior.attrs));

        let mut clauses = Vec::new();
        for clause in &behavior.clauses {
            clauses.push(self.lower_clause(clause));
        }

        let id = format!("{}/behavior/{}", self.module_name, behavior.name.text);

        Some(IrNode::new(
            id,
            "behavior",
            behavior.name.text.clone(),
            fields,
            clauses,
        ))
    }

    fn lower_clause(&self, clause: &Clause) -> Sexpr {
        match clause {
            Clause::Requires(pred) => {
                Sexpr::list(vec![Sexpr::sym("requires"), pred_to_sexpr(pred)])
            }
            Clause::Ensures(pred) => Sexpr::list(vec![Sexpr::sym("ensures"), pred_to_sexpr(pred)]),
            Clause::Returns(expr) => Sexpr::list(vec![Sexpr::sym("returns"), expr_to_sexpr(expr)]),
            Clause::Fails {
                error,
                when,
                preserves,
            } => {
                let mut items = vec![
                    Sexpr::sym("fails"),
                    Sexpr::sym(&error.text),
                    Sexpr::sym(":when"),
                    pred_to_sexpr(when),
                ];
                if let Some(preserve_ident) = preserves {
                    items.push(Sexpr::sym(":preserves"));
                    items.push(Sexpr::sym(&preserve_ident.text));
                }
                Sexpr::list(items)
            }
            Clause::Emits { event, qualifier } => {
                let mut items = vec![Sexpr::sym("emits"), Sexpr::sym(&event.text)];
                for q in qualifier {
                    items.push(Sexpr::sym(&q.text));
                }
                Sexpr::list(items)
            }
        }
    }

    fn lower_invariant(&self, inv: &InvariantDecl) -> Option<IrNode> {
        let fields = vec![
            (":scope".to_string(), Sexpr::sym(&inv.scope.text)),
            (":always".to_string(), pred_to_sexpr(&inv.always)),
        ];
        let id = format!("{}/invariant/{}", self.module_name, inv.name.text);

        Some(IrNode::new(
            id,
            "invariant",
            inv.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_constraint(&self, constr: &ConstraintDecl) -> Option<IrNode> {
        let mut fields = vec![
            (":class".to_string(), Sexpr::sym(&constr.class.text)),
            (":scope".to_string(), Sexpr::sym(&constr.scope.text)),
        ];

        // :under as nested list of (key value) pairs
        let mut under_pairs = Vec::new();
        for item in &constr.under {
            let key = item.key.text.clone();
            let value = pack_value_to_sexpr(&item.value);
            under_pairs.push(Sexpr::list(vec![Sexpr::sym(&key), value]));
        }
        fields.push((":under".to_string(), Sexpr::list(under_pairs)));

        fields.push((":must".to_string(), pred_to_sexpr(&constr.must)));

        let id = format!("{}/constraint/{}", self.module_name, constr.name.text);

        Some(IrNode::new(
            id,
            "constraint",
            constr.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_synthesis(&self, synth: &SynthesisDecl) -> Option<IrNode> {
        let mut target_items = vec![Sexpr::sym(&synth.target_lang.text)];
        if let Some(framework) = &synth.target_framework {
            target_items.push(Sexpr::sym(&framework.text));
        }
        let target_value = Sexpr::list(target_items);

        let mut fields = vec![(":target".to_string(), target_value)];
        fields.extend(pack_to_fields(&synth.attrs));

        let id = format!("{}/synthesis/{}", self.module_name, synth.name.text);

        Some(IrNode::new(
            id,
            "synthesis",
            synth.name.text.clone(),
            fields,
            vec![],
        ))
    }

    fn lower_acceptance(&self, acc: &AcceptanceDecl) -> Option<IrNode> {
        let fields = vec![(":subject".to_string(), Sexpr::sym(&acc.subject.text))];

        let mut clauses = Vec::new();
        for block in &acc.blocks {
            clauses.push(self.lower_acceptance_block(block));
        }

        let id = format!("{}/acceptance/{}", self.module_name, acc.name.text);

        Some(IrNode::new(
            id,
            "acceptance",
            acc.name.text.clone(),
            fields,
            clauses,
        ))
    }

    fn lower_acceptance_block(&self, block: &AcceptanceBlock) -> Sexpr {
        match block {
            AcceptanceBlock::Property { name, body } => {
                let mut items = vec![Sexpr::sym("property"), Sexpr::sym(&name.text)];
                for item in body {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Scenario { name, steps } => {
                let mut items = vec![Sexpr::sym("scenario"), Sexpr::sym(&name.text)];
                for item in steps {
                    items.push(Sexpr::list(vec![
                        Sexpr::sym(&item.key.text),
                        pack_value_to_sexpr(&item.value),
                    ]));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Concurrency { name, attrs, must } => {
                let mut items = vec![Sexpr::sym("concurrency"), Sexpr::sym(&name.text)];
                for item in attrs {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                items.push(Sexpr::sym(":must"));
                items.push(pred_to_sexpr(must));
                Sexpr::list(items)
            }
            AcceptanceBlock::Fault { name, body, must } => {
                let mut items = vec![Sexpr::sym("fault"), Sexpr::sym(&name.text)];
                for item in body {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                if let Some(pred) = must {
                    items.push(Sexpr::sym(":must"));
                    items.push(pred_to_sexpr(pred));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Coverage(names) => {
                // Keyword pairs, so a port of verify.lisp's
                // gymnast-keyword-value reads them unchanged.
                let mut items = vec![Sexpr::sym("coverage")];
                for name in names {
                    items.push(Sexpr::sym(&format!(":{}", name.text)));
                    items.push(Sexpr::sym("t"));
                }
                Sexpr::list(items)
            }
            AcceptanceBlock::Execution(pack) => {
                let mut items = vec![Sexpr::sym("execution")];
                for item in pack {
                    items.push(Sexpr::sym(&format!(":{}", item.key.text)));
                    items.push(pack_value_to_sexpr(&item.value));
                }
                Sexpr::list(items)
            }
        }
    }
}

// Helper functions

/// Keys whose values are lists in the Lamedh IR contract. A single
/// element still lowers as a one-element list, so downstream iteration
/// never has to special-case arity 1.
fn is_plural_field(key: &str) -> bool {
    matches!(
        key,
        "provides" | "uses" | "grant" | "deny" | "modules" | "reads" | "writes"
    )
}

/// The duration/latency unit names the surface grammar knows (the same
/// set `parser.rs` folds into `PackValue::Quantity`).
fn is_duration_unit(name: &str) -> bool {
    matches!(name, "min" | "ms" | "s" | "sec")
}

fn pack_to_fields(pack: &Pack) -> Vec<(String, Sexpr)> {
    let mut fields = Vec::new();
    for item in pack {
        let key = format!(":{}", item.key.text);
        let mut value = pack_value_to_sexpr(&item.value);
        if is_plural_field(&item.key.text) && !matches!(value, Sexpr::List(_)) {
            value = Sexpr::list(vec![value]);
        }
        fields.push((key, value));
    }
    fields
}

fn pack_value_to_sexpr(value: &PackValue) -> Sexpr {
    match value {
        PackValue::Unit => Sexpr::sym("t"),
        PackValue::Word(w) => Sexpr::sym(&w.text),
        PackValue::Int(i) => Sexpr::Int(*i),
        PackValue::Str(s) => Sexpr::Str(s.clone()),
        PackValue::Quantity { value, unit } => {
            Sexpr::list(vec![Sexpr::sym(&unit.text), Sexpr::Int(*value)])
        }
        PackValue::List(items) => {
            let sexprs: Vec<Sexpr> = items.iter().map(|v| pack_value_to_sexpr(v)).collect();
            Sexpr::list(sexprs)
        }
        PackValue::Path(segs) => {
            let path_str = segs
                .iter()
                .map(|s| s.text.clone())
                .collect::<Vec<_>>()
                .join("/");
            Sexpr::sym(&path_str)
        }
        PackValue::Call { name, args } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            for arg in args {
                items.push(pack_value_to_sexpr(arg));
            }
            Sexpr::list(items)
        }
        PackValue::Nested(pack) => {
            let mut pairs = Vec::new();
            for item in pack {
                let key = item.key.text.clone();
                let value = pack_value_to_sexpr(&item.value);
                pairs.push(Sexpr::list(vec![Sexpr::sym(&key), value]));
            }
            Sexpr::list(pairs)
        }
    }
}

/// The declaration-level shape field: exactly one of :opaque, :enum,
/// :variant, or :record, mirroring the Lamedh type vocabulary.
fn mode_expr_to_shape_field(expr: &ModeExpr) -> (String, Sexpr) {
    match expr {
        ModeExpr::Opaque(inner) => (":opaque".to_string(), mode_expr_to_sexpr(inner)),
        ModeExpr::Enum(names) => {
            let syms: Vec<Sexpr> = names.iter().map(|n| Sexpr::sym(&n.text)).collect();
            (":enum".to_string(), Sexpr::list(syms))
        }
        ModeExpr::Union(variants) => {
            let pairs: Vec<Sexpr> = variants
                .iter()
                .map(|(tag, mode)| {
                    Sexpr::list(vec![Sexpr::sym(&tag.text), mode_expr_to_sexpr(mode)])
                })
                .collect();
            (":variant".to_string(), Sexpr::list(pairs))
        }
        ModeExpr::Struct(fields) => {
            let pairs: Vec<Sexpr> = fields
                .iter()
                .map(|f| Sexpr::list(vec![Sexpr::sym(&f.name.text), mode_expr_to_sexpr(&f.mode)]))
                .collect();
            (":record".to_string(), Sexpr::list(pairs))
        }
        other => (":opaque".to_string(), mode_expr_to_sexpr(other)),
    }
}

fn mode_expr_to_sexpr(expr: &ModeExpr) -> Sexpr {
    match expr {
        ModeExpr::Named { name, args } => {
            if args.is_empty() {
                Sexpr::sym(&name.text)
            } else {
                let mut items = vec![Sexpr::sym(&name.text)];
                for arg in args {
                    items.push(mode_expr_to_sexpr(arg));
                }
                Sexpr::list(items)
            }
        }
        ModeExpr::Refined { name, lo, hi } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            if let Some(lower) = lo {
                items.push(Sexpr::sym(":min"));
                items.push(Sexpr::Int(*lower));
            }
            if let Some(upper) = hi {
                items.push(Sexpr::sym(":max"));
                items.push(Sexpr::Int(*upper));
            }
            Sexpr::list(items)
        }
        ModeExpr::RefinedSym { name, lo, hi } => {
            // v0.2 constant-referencing refinement bounds lower with the
            // bound NAME in the `:min`/`:max` value slot; the
            // substitution pass resolves it to the literal (or E209) so
            // downstream consumers only ever see the `Refined` shape.
            let bound = |b: &RefBound| match b {
                RefBound::Int(v) => Sexpr::Int(*v),
                RefBound::Name(n) => Sexpr::sym(&n.text),
            };
            let mut items = vec![Sexpr::sym(&name.text)];
            if let Some(lower) = lo {
                items.push(Sexpr::sym(":min"));
                items.push(bound(lower));
            }
            if let Some(upper) = hi {
                items.push(Sexpr::sym(":max"));
                items.push(bound(upper));
            }
            Sexpr::list(items)
        }
        ModeExpr::Opt(inner) => {
            Sexpr::list(vec![Sexpr::sym("Optional"), mode_expr_to_sexpr(inner)])
        }
        ModeExpr::Row(inner) => Sexpr::list(vec![Sexpr::sym("Row"), mode_expr_to_sexpr(inner)]),
        ModeExpr::Opaque(inner) => {
            Sexpr::list(vec![Sexpr::sym("opaque"), mode_expr_to_sexpr(inner)])
        }
        ModeExpr::Enum(names) => {
            let syms: Vec<Sexpr> = names.iter().map(|n| Sexpr::sym(&n.text)).collect();
            Sexpr::list(vec![Sexpr::sym("enum"), Sexpr::list(syms)])
        }
        ModeExpr::Union(variants) => {
            let pairs: Vec<Sexpr> = variants
                .iter()
                .map(|(tag, mode)| {
                    Sexpr::list(vec![Sexpr::sym(&tag.text), mode_expr_to_sexpr(mode)])
                })
                .collect();
            Sexpr::list(vec![Sexpr::sym("variant"), Sexpr::list(pairs)])
        }
        ModeExpr::Struct(fields) => {
            let mut field_pairs = Vec::new();
            for field in fields {
                let name = &field.name.text;
                let mode = mode_expr_to_sexpr(&field.mode);
                field_pairs.push(Sexpr::list(vec![Sexpr::sym(name), mode]));
            }
            Sexpr::list(vec![Sexpr::sym("record"), Sexpr::list(field_pairs)])
        }
    }
}

fn pred_to_sexpr(pred: &Pred) -> Sexpr {
    match pred {
        Pred::Cmp { op, lhs, rhs } => {
            let op_str = match op {
                CmpOp::Eq => "=",
                CmpOp::Lt => "<",
                CmpOp::Le => "<=",
            };
            Sexpr::list(vec![
                Sexpr::sym(op_str),
                expr_to_sexpr(lhs),
                expr_to_sexpr(rhs),
            ])
        }
        Pred::And(a, b) => Sexpr::list(vec![Sexpr::sym("and"), pred_to_sexpr(a), pred_to_sexpr(b)]),
        Pred::Or(a, b) => Sexpr::list(vec![Sexpr::sym("or"), pred_to_sexpr(a), pred_to_sexpr(b)]),
        Pred::Not(p) => Sexpr::list(vec![Sexpr::sym("not"), pred_to_sexpr(p)]),
        Pred::ForAll { mode, var, body } => Sexpr::list(vec![
            Sexpr::sym("forall"),
            Sexpr::list(vec![Sexpr::list(vec![
                Sexpr::sym(&var.text),
                Sexpr::sym(&mode.text),
            ])]),
            pred_to_sexpr(body),
        ]),
        Pred::Exists { mode, var, body } => Sexpr::list(vec![
            Sexpr::sym("exists"),
            Sexpr::list(vec![Sexpr::list(vec![
                Sexpr::sym(&var.text),
                Sexpr::sym(&mode.text),
            ])]),
            pred_to_sexpr(body),
        ]),
        Pred::Call { name, args } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            for arg in args {
                items.push(expr_to_sexpr(arg));
            }
            Sexpr::list(items)
        }
        Pred::Word(w) => Sexpr::sym(&w.text),
    }
}

fn expr_to_sexpr(expr: &Expr) -> Sexpr {
    match expr {
        Expr::Int(i) => Sexpr::Int(*i),
        Expr::Str(s) => Sexpr::Str(s.clone()),
        Expr::Path(segs) => {
            let path_str = segs
                .iter()
                .map(|s| s.text.clone())
                .collect::<Vec<_>>()
                .join("/");
            Sexpr::sym(&path_str)
        }
        Expr::Call { name, args } => {
            let mut items = vec![Sexpr::sym(&name.text)];
            for arg in args {
                items.push(expr_to_sexpr(arg));
            }
            Sexpr::list(items)
        }
    }
}

/// The source span of a declaration, for elaboration diagnostics.
fn decl_span(decl: &Decl) -> crate::span::Span {
    match decl {
        Decl::Use(d) => d.span,
        Decl::Const(d) => d.span,
        Decl::Application(d) => d.span,
        Decl::Actor(d) => d.span,
        Decl::Mode(d) => d.span,
        Decl::Component(d) => d.span,
        Decl::Interface(d) => d.span,
        Decl::State(d) => d.span,
        Decl::Flow(d) => d.span,
        Decl::Behavior(d) => d.span,
        Decl::Invariant(d) => d.span,
        Decl::Constraint(d) => d.span,
        Decl::Synthesis(d) => d.span,
        Decl::Acceptance(d) => d.span,
    }
}

fn lower_diagnostics(diags: &[Diagnostic]) -> Vec<Sexpr> {
    let mut result = Vec::new();
    for diag in diags {
        let severity_str = match diag.severity {
            Severity::Error => "error",
            Severity::Warning => "warning",
        };
        let diag_sexpr = crate::diag::diag_sexpr(
            severity_str,
            diag.code,
            (diag.span.start as i64, diag.span.end as i64),
            diag.message.clone(),
        );
        result.push(diag_sexpr);
    }
    result
}
