;;; Deterministic recipe registry and executor.
;;;
;;; Recipes are named, versioned transformation functions registered
;;; by stable identity.  Structural, assembly, and verification
;;; recipes execute deterministically without model access.
;;; Generative recipes produce prompt packages for the model runner.
;;;
;;; Execution records recipe and tool identity in evidence for
;;; the trust boundary.

(def $gymnast-recipe-registry nil)

;;; Target-language dispatch.
;;;
;;; A target record identifies the emission target; protocols dispatch
;;; on the target's type so new target languages can be added by
;;; defining a new record and a matching set of definstance bodies,
;;; without touching the executor functions below.

(defrecord gymnast-ruby-target name)

(def $gymnast-ruby-target (make-gymnast-ruby-target 'ruby))

(defprotocol gymnast-emit-comment-header)
(defprotocol gymnast-emit-type-declaration)
(defprotocol gymnast-emit-operation-signature)

(defun gymnast-register-recipe (name class executor)
  (let ((entry (list 'recipe
          (list 'name name)
          (list 'class class)
          (list 'executor executor))))
    (setq $gymnast-recipe-registry
      (cons entry
        (filter (lambda (r)
            (not (equal (gymnast-assoc-value 'name (cdr r)) name)))
          $gymnast-recipe-registry)))
    entry))

(defun gymnast-lookup-recipe (name)
  (let ((matches
        (filter (lambda (r)
            (equal (gymnast-assoc-value 'name (cdr r)) name))
          $gymnast-recipe-registry)))
    (if matches (car matches) nil)))

(defun gymnast-recipe-field (recipe key)
  (gymnast-assoc-value key (cdr recipe)))

(defun gymnast-recipe-requires-model-p (recipe)
  (equal (gymnast-recipe-field recipe 'class) 'generative))

;;; Execution: produce a candidate from a plan node.

(defun gymnast-execute-recipe (ir plan node)
  (let* ((recipe-name (gymnast-plan-node-field node 'recipe))
      (recipe (gymnast-lookup-recipe recipe-name))
      (node-id (gymnast-plan-node-id node)))
    (if (not recipe)
      (list 'execution-result
        (list 'node-id node-id)
        (list 'status 'failed)
        (list 'diagnostics
          (list (gymnast-diagnostic 'error 'unknown-recipe node-id
              (concat "no registered recipe: "
                (princ-to-string recipe-name))
              recipe-name))))
      (if (gymnast-recipe-requires-model-p recipe)
        (list 'execution-result
          (list 'node-id node-id)
          (list 'status 'deferred)
          (list 'reason 'requires-model))
        (let* ((executor (gymnast-recipe-field recipe 'executor))
            (ir-slice (gymnast-node-ir-slice ir node))
            (candidate (funcall executor ir-slice node)))
          (let ((diagnostics
                (gymnast-candidate-diagnostics node candidate)))
            (list 'execution-result
              (list 'node-id node-id)
              (list 'status (if (gymnast-has-errors-p diagnostics)
                  'failed 'succeeded))
              (list 'candidate candidate)
              (list 'recipe-identity recipe-name)
              (list 'diagnostics diagnostics))))))))

(defun gymnast-execution-result-field (result key)
  (gymnast-assoc-value key (cdr result)))

;;; Execute all deterministic nodes in a plan.

(defun gymnast-execute-deterministic (ir plan)
  (let ((nodes (gymnast-plan-field plan 'nodes)))
    (mapcar (lambda (node) (gymnast-execute-recipe ir plan node))
      nodes)))

(defun gymnast-deterministic-results (results)
  (filter (lambda (r)
      (not (equal (gymnast-execution-result-field r 'status) 'deferred)))
    results))

(defun gymnast-deferred-results (results)
  (filter (lambda (r)
      (equal (gymnast-execution-result-field r 'status) 'deferred))
    results))

;;; Built-in structural recipes.

(definstance gymnast-emit-comment-header ((target gymnast-ruby-target) title)
  string
  (let ((nl (code-char 10)))
    (concat "# frozen_string_literal: true" nl
      "# Generated by gymnast — do not edit." nl
      "# " title nl nl)))

(definstance gymnast-emit-type-declaration
  ((target gymnast-ruby-target) ir-node)
  string
  (let* ((name (gymnast-ir-node-field ir-node 'name))
      (fields (gymnast-ir-node-field ir-node 'fields))
      (shape-key (cond
          ((assoc ':opaque fields) ':opaque)
          ((assoc ':record fields) ':record)
          ((assoc ':enum fields) ':enum)
          ((assoc ':variant fields) ':variant)
          (t nil)))
      (shape-value (if shape-key (gymnast-assoc-value shape-key fields) nil))
      (nl (code-char 10)))
    (cond
      ((equal shape-key ':opaque)
        (concat "  " (princ-to-string name) " = String" nl))
      ((equal shape-key ':enum)
        (concat "  " (princ-to-string name)
          " = %i[" (gymnast-join-strings
            (mapcar #'gymnast-symbol-string shape-value) " ")
          "].freeze" nl))
      ((equal shape-key ':record)
        (concat "  " (princ-to-string name)
          " = Struct.new("
          (gymnast-join-strings
            (mapcar (lambda (field)
                (concat ":" (gymnast-symbol-string (car field))))
              shape-value)
            ", ")
          ", keyword_init: true)" nl))
      (t (concat "  # " (princ-to-string name) " (variant)" nl)))))

(defun gymnast-ruby-comment-header (title)
  (gymnast-emit-comment-header $gymnast-ruby-target title))

(defun gymnast-ruby-type-declaration (ir-node)
  (gymnast-emit-type-declaration $gymnast-ruby-target ir-node))

(defun gymnast-design-contracts-executor (ir-slice node)
  (let* ((nl (code-char 10))
      (types (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'type)) ir-slice))
      (actors (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'actor)) ir-slice))
      (components (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'component)) ir-slice))
      (type-code (gymnast-join-strings
          (mapcar (lambda (n)
              (gymnast-emit-type-declaration $gymnast-ruby-target n))
            types) ""))
      (actor-code (gymnast-join-strings
          (mapcar (lambda (a)
              (concat "  # Actor: "
                (princ-to-string (gymnast-ir-node-field a 'name)) nl))
            actors) ""))
      (component-code (gymnast-join-strings
          (mapcar (lambda (c)
              (let ((name (gymnast-ir-node-field c 'name))
                  (resp (gymnast-surface-field c ':responsibility)))
                (concat "  # Component: "
                  (princ-to-string name) " — "
                  (if (stringp resp) resp (princ-to-string resp)) nl)))
            components) ""))
      (content (concat
          (gymnast-emit-comment-header $gymnast-ruby-target "Design contracts")
          "module Contracts" nl
          actor-code nl
          "  # Types" nl type-code nl
          component-code
          "end" nl))
      (paths (gymnast-plan-node-field node 'may-write)))
    (list 'candidate
      (list 'schema $gymnast-candidate-schema)
      (list 'node-id (gymnast-plan-node-id node))
      (list 'files (list (list (car paths) content)))
      (list 'implements
        (mapcar #'gymnast-ir-node-id ir-slice))
      (list 'edge-uses nil)
      (list 'assumptions nil)
      (list 'unresolved nil))))

(gymnast-register-recipe 'design-contracts-v1 'structural
  #'gymnast-design-contracts-executor)

;;; Interface contracts recipe.

(definstance gymnast-emit-operation-signature
  ((target gymnast-ruby-target) clause)
  string
  (let* ((kind (car clause))
      (name (cadr clause))
      (rest (cdr (cdr clause)))
      (actor (gymnast-keyword-value rest ':actor))
      (input (gymnast-keyword-value rest ':input))
      (output (gymnast-keyword-value rest ':output))
      (nl (code-char 10)))
    (concat "    def "
      (gymnast-symbol-string name)
      "(" (if actor (gymnast-symbol-string actor) "") ", "
      (if input (princ-to-string input) "nil") ")"
      nl
      "      raise NotImplementedError"
      nl "    end" nl)))

(defun gymnast-ruby-operation-signature (clause)
  (gymnast-emit-operation-signature $gymnast-ruby-target clause))

(defun gymnast-interface-contracts-executor (ir-slice node)
  (let* ((nl (code-char 10))
      (interfaces (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'interface)) ir-slice))
      (content (concat
          (gymnast-emit-comment-header $gymnast-ruby-target "Interface contracts")
          (gymnast-join-strings
            (mapcar (lambda (iface)
                (let* ((name (gymnast-ir-node-field iface 'name))
                    (clauses (gymnast-ir-node-field iface 'clauses))
                    (ops (gymnast-join-strings
                        (mapcar (lambda (c)
                            (gymnast-emit-operation-signature $gymnast-ruby-target c))
                          clauses) nl)))
                  (concat "  module "
                    (princ-to-string name) nl
                    "    class Service" nl ops
                    "    end" nl "  end" nl)))
              interfaces) nl)))
      (paths (gymnast-plan-node-field node 'may-write)))
    (list 'candidate
      (list 'schema $gymnast-candidate-schema)
      (list 'node-id (gymnast-plan-node-id node))
      (list 'files (list (list (car paths) content)))
      (list 'implements
        (mapcar #'gymnast-ir-node-id ir-slice))
      (list 'edge-uses nil)
      (list 'assumptions nil)
      (list 'unresolved nil))))

(gymnast-register-recipe 'interface-contracts-v1 'structural
  #'gymnast-interface-contracts-executor)

;;; Acceptance harness recipe.

(defun gymnast-acceptance-harness-executor (ir-slice node)
  (let* ((nl (code-char 10))
      (behaviors (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'behavior)) ir-slice))
      (invariants (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'invariant)) ir-slice))
      (acceptances (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'acceptance)) ir-slice))
      (content (concat
          (gymnast-emit-comment-header $gymnast-ruby-target "Acceptance harness")
          "require_relative '../gymnast_platform'" nl
          "require_relative '../../platform/ruby/test_doubles/all'" nl nl
          "module AcceptanceHarness" nl
          "  def self.run(service)" nl
          (gymnast-join-strings
            (mapcar (lambda (b)
                (concat "    # Behavior: "
                  (princ-to-string (gymnast-ir-node-id b)) nl))
              behaviors) "")
          (gymnast-join-strings
            (mapcar (lambda (inv)
                (concat "    # Invariant: "
                  (princ-to-string (gymnast-ir-node-id inv)) nl))
              invariants) "")
          (gymnast-join-strings
            (mapcar (lambda (acc)
                (let ((clauses (gymnast-ir-node-field acc 'clauses)))
                  (gymnast-join-strings
                    (mapcar (lambda (clause)
                        (concat "    # " (princ-to-string (car clause))
                          ": " (princ-to-string (cadr clause)) nl))
                      clauses) "")))
              acceptances) "")
          "    { status: :pass, behaviors: "
          (princ-to-string (length behaviors))
          ", invariants: " (princ-to-string (length invariants))
          " }" nl
          "  end" nl "end" nl))
      (paths (gymnast-plan-node-field node 'may-write)))
    (list 'candidate
      (list 'schema $gymnast-candidate-schema)
      (list 'node-id (gymnast-plan-node-id node))
      (list 'files (list (list (car paths) content)))
      (list 'implements
        (mapcar #'gymnast-ir-node-id ir-slice))
      (list 'edge-uses nil)
      (list 'assumptions nil)
      (list 'unresolved nil))))

(gymnast-register-recipe 'acceptance-harness-v1 'verification
  #'gymnast-acceptance-harness-executor)

;;; Application assembly recipe.

(defun gymnast-application-assembly-executor (ir-slice node)
  (let* ((nl (code-char 10))
      (apps (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'application)) ir-slice))
      (syntheses (filter (lambda (n)
            (equal (gymnast-ir-node-kind n) 'synthesis)) ir-slice))
      (app-name (if apps
          (gymnast-ir-node-field (car apps) 'name)
          'application))
      (content (concat
          (gymnast-emit-comment-header $gymnast-ruby-target "Application assembly")
          "require_relative 'gymnast_platform'" nl nl
          "module " (princ-to-string app-name) nl
          "  def self.boot(registry = GymnastPlatform.registry)" nl
          "    lifecycle = registry.resolve(:lifecycle)" nl
          "    lifecycle.start(dependencies: ["
          ":identity, :persistence, :http])" nl
          "    self" nl
          "  end" nl nl
          "  def self.shutdown" nl
          "    GymnastPlatform.resolve(:lifecycle).stop" nl
          "  end" nl
          "end" nl))
      (manifest (concat
          "(manifest" nl
          "  (application " (princ-to-string app-name) ")" nl
          "  (platform gymnast-ruby-platform-v1)" nl
          "  (artifacts"
          (gymnast-join-strings
            (mapcar (lambda (n)
                (concat nl "    " (princ-to-string (gymnast-ir-node-id n))))
              ir-slice) "")
          "))" nl))
      (paths (gymnast-plan-node-field node 'may-write)))
    (list 'candidate
      (list 'schema $gymnast-candidate-schema)
      (list 'node-id (gymnast-plan-node-id node))
      (list 'files
        (list (list (car paths) content)
          (list (cadr paths) manifest)))
      (list 'implements
        (mapcar #'gymnast-ir-node-id ir-slice))
      (list 'edge-uses nil)
      (list 'assumptions nil)
      (list 'unresolved nil))))

(gymnast-register-recipe 'application-assembly-v1 'assembly
  #'gymnast-application-assembly-executor)

;;; Register generative recipes as placeholders (executed by model runner).

(gymnast-register-recipe 'transition-kernel-v1 'generative nil)
(gymnast-register-recipe 'authorization-policy-v1 'generative nil)
(gymnast-register-recipe 'persistence-v1 'generative nil)
(gymnast-register-recipe 'service-handlers-v1 'generative nil)
